project: 
  type: book
  
book: 
  page-navigation: true
  title: "Applied Statistics"
  author: "Robin Donatello, Edward Roualdes"
  date: last-modified
  description: "Course notes for Applied Statistics courses at CSU Chico"
  chapters:
    - href: index.qmd
    - part: "Preparing Data for Analysis"
      chapters: 
        - href: dataprep.qmd
        - href: data_viz.qmd
#    
#    - href: dataprep.qmd
#    - href: data_viz.qmd

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
#  site-url: "https://openscapes.github.io/quarto-website-tutorial" 
#  repo-url: https://github.com/openscapes/quarto-website-tutorial 
#  repo-actions: [edit, issue]

#bibliography 

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

  
