<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.319">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Course notes for various Applied Statistics courses at CSU Chico">

<title>Applied Statistics - 5&nbsp; Bivariate Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./foundations.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./foundations.html">Statistical Inference</a></li><li class="breadcrumb-item"><a href="./bivariate_analysis.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bivariate Analysis</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Applied Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/annakfell/ascnv2" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Preparing Data for Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataprep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Workflow and Data Cleaning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Visualizing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./select_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Selecting Appropriate Analyses</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bivariate Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#assumption-of-independent-observations" id="toc-assumption-of-independent-observations" class="nav-link active" data-scroll-target="#assumption-of-independent-observations"><span class="header-section-number">5.1</span> Assumption of Independent Observations</a></li>
  <li><a href="#choosing-appropriate-bivariate-analysis" id="toc-choosing-appropriate-bivariate-analysis" class="nav-link" data-scroll-target="#choosing-appropriate-bivariate-analysis"><span class="header-section-number">5.2</span> Choosing appropriate bivariate analysis</a></li>
  <li><a href="#bv-ttest" id="toc-bv-ttest" class="nav-link" data-scroll-target="#bv-ttest"><span class="header-section-number">5.3</span> (Q~B) Two means: T-Test</a>
  <ul>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">5.3.1</span> Assumptions</a></li>
  <li><a href="#sampling-distribution-for-the-difference" id="toc-sampling-distribution-for-the-difference" class="nav-link" data-scroll-target="#sampling-distribution-for-the-difference"><span class="header-section-number">5.3.2</span> Sampling Distribution for the difference</a></li>
  <li><a href="#example-smoking-and-bmi" id="toc-example-smoking-and-bmi" class="nav-link" data-scroll-target="#example-smoking-and-bmi"><span class="header-section-number">5.3.3</span> Example: Smoking and BMI</a></li>
  </ul></li>
  <li><a href="#bv-anova" id="toc-bv-anova" class="nav-link" data-scroll-target="#bv-anova"><span class="header-section-number">5.4</span> (Q~C) Multiple means: ANOVA</a>
  <ul>
  <li><a href="#example-visual-comparison" id="toc-example-visual-comparison" class="nav-link" data-scroll-target="#example-visual-comparison"><span class="header-section-number">5.4.0.1</span> Example: Visual Comparison</a></li>
  <li><a href="#formulation-of-the-one-way-anova-model" id="toc-formulation-of-the-one-way-anova-model" class="nav-link" data-scroll-target="#formulation-of-the-one-way-anova-model"><span class="header-section-number">5.4.1</span> Formulation of the One-way ANOVA model</a></li>
  <li><a href="#analysis-of-variance-table" id="toc-analysis-of-variance-table" class="nav-link" data-scroll-target="#analysis-of-variance-table"><span class="header-section-number">5.4.2</span> Analysis of Variance Table*:</a></li>
  <li><a href="#the-f-distribution" id="toc-the-f-distribution" class="nav-link" data-scroll-target="#the-f-distribution"><span class="header-section-number">5.4.3</span> The F-distribution</a></li>
  <li><a href="#assumptions-1" id="toc-assumptions-1" class="nav-link" data-scroll-target="#assumptions-1"><span class="header-section-number">5.4.4</span> Assumptions</a></li>
  <li><a href="#example-a-comparison-of-plant-species-under-low-water-conditions" id="toc-example-a-comparison-of-plant-species-under-low-water-conditions" class="nav-link" data-scroll-target="#example-a-comparison-of-plant-species-under-low-water-conditions"><span class="header-section-number">5.4.5</span> Example: A comparison of plant species under low water conditions</a></li>
  <li><a href="#coefficient-of-determination-r2" id="toc-coefficient-of-determination-r2" class="nav-link" data-scroll-target="#coefficient-of-determination-r2"><span class="header-section-number">5.4.6</span> Coefficient of determination <span class="math inline">\(R^{2}\)</span></a></li>
  <li><a href="#multiple-comparisons" id="toc-multiple-comparisons" class="nav-link" data-scroll-target="#multiple-comparisons"><span class="header-section-number">5.4.7</span> Multiple Comparisons</a></li>
  </ul></li>
  <li><a href="#bv-chisq" id="toc-bv-chisq" class="nav-link" data-scroll-target="#bv-chisq"><span class="header-section-number">5.5</span> (C~C) Multiple Proportions: <span class="math inline">\(\chi^{2}\)</span></a>
  <ul>
  <li><a href="#conditions-for-the-sampling-distribution-to-be-normal." id="toc-conditions-for-the-sampling-distribution-to-be-normal." class="nav-link" data-scroll-target="#conditions-for-the-sampling-distribution-to-be-normal."><span class="header-section-number">5.5.1</span> Conditions for the sampling distribution to be normal.</a></li>
  <li><a href="#example-are-mammograms-effective" id="toc-example-are-mammograms-effective" class="nav-link" data-scroll-target="#example-are-mammograms-effective"><span class="header-section-number">5.5.2</span> Example: Are Mammograms effective?</a></li>
  <li><a href="#example-smoking-and-general-health" id="toc-example-smoking-and-general-health" class="nav-link" data-scroll-target="#example-smoking-and-general-health"><span class="header-section-number">5.5.3</span> Example: Smoking and General Health</a></li>
  <li><a href="#multiple-comparisons-1" id="toc-multiple-comparisons-1" class="nav-link" data-scroll-target="#multiple-comparisons-1"><span class="header-section-number">5.5.4</span> Multiple Comparisons</a></li>
  </ul></li>
  <li><a href="#bv-corr" id="toc-bv-corr" class="nav-link" data-scroll-target="#bv-corr"><span class="header-section-number">5.6</span> (Q~Q) Correlation</a>
  <ul>
  <li><a href="#strength-of-the-correlation" id="toc-strength-of-the-correlation" class="nav-link" data-scroll-target="#strength-of-the-correlation"><span class="header-section-number">5.6.1</span> Strength of the correlation</a></li>
  <li><a href="#example-federal-spending-per-capita-and-poverty-rate" id="toc-example-federal-spending-per-capita-and-poverty-rate" class="nav-link" data-scroll-target="#example-federal-spending-per-capita-and-poverty-rate"><span class="header-section-number">5.6.2</span> Example: Federal spending per capita and poverty rate</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/annakfell/ascnv2/edit/main/bivariate_analysis.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/annakfell/ascnv2/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-bivariate-analysis" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bivariate Analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>So far we have been concerned with making inference about a single population parameter. Many problems deal with comparing a parameter across two or more groups. Research questions include questions like:</p>
<ul>
<li>Does the average life span differ across subspecies of a particular turtle?</li>
<li>Who has a higher percentage of the female vote - Democrats or Republicans?</li>
</ul>
<p>A good way to think about all statistical models is that the observed data comes from some true model with some random error.</p>
<blockquote class="blockquote">
<p>DATA = MODEL + RESIDUAL</p>
</blockquote>
<p>The <code>MODEL</code> is a mathematical formula (like <span class="math inline">\(y = f(x)\)</span>). The formulation of the <code>MODEL</code> will change depending on the number of, and data types of explanatory variables. One goal of inferential analysis is to explain the variation in our data, using information contained in other measures.</p>
<section id="assumption-of-independent-observations" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="assumption-of-independent-observations"><span class="header-section-number">5.1</span> Assumption of Independent Observations</h2>
<p>The primary assumption of most standard statistical procedures is that observations are independent of each other. That is, the value of one observation does not change or affect another observation. However, there are many examples where measurements are made on subjects before and after a certain exposure or treatment (pre-post), or an experiment to compare two cell phone packages might use pairs of subjects that are the same age, sex and income level. One subject would be randomly assigned to the first phone package, the other in the pair would get the second phone package. This chapter only deals with non-correlated analyses, leaving that topic for a later chapter.</p>
</section>
<section id="choosing-appropriate-bivariate-analysis" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="choosing-appropriate-bivariate-analysis"><span class="header-section-number">5.2</span> Choosing appropriate bivariate analysis</h2>
<p>Choosing which statistical analyses procedure is appropriate completely depending on the data types of the explanatory and response variable. This is a simplified table, only covering the common/standard types of bivariate analysis.</p>
<blockquote class="blockquote">
<p>figure out how to get table here.</p>
</blockquote>
<p>For this set of notes, the variable types are referred to using the first letter, e.g.&nbsp;<em>Q</em> for quantitative, <em>B</em> for binary, and <em>C</em> for categorical. Thus a T-test is a (Q <span class="math inline">\(\sim\)</span> B) analysis, and a correlation analysis is (Q <span class="math inline">\(\sim\)</span> Q) analysis.</p>
<p>Links to the example data used in this chapter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"_common.R"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'addhealth_clean.Rdata'</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>county <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://www.norcalbiostat.com/data/countyComplete.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-warning">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<blockquote class="blockquote">
<p>county dataset will need to be replaced or example switched - no longer included in openintro &amp; the csv on https://www.norcalbiostat.com/data/#countyComplete is missing federal spending column</p>
</blockquote>
</div>
</div>
</div>
<hr>
</section>
<section id="bv-ttest" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="bv-ttest"><span class="header-section-number">5.3</span> (Q~B) Two means: T-Test</h2>
<p>It is common to compare means from different samples. For instance, we might investigate the effectiveness of a certain educational intervention by looking for evidence of greater reading ability in the treatment group against a control group. That is, our research hypothesis is that reading ability of a child is associated with an educational intervention.</p>
<p>The null hypothesis states that there is no relationship, or no effect, of the educational intervention (binary explanatory variable) on the reading ability of the child (quantitative response variable). This can be written in symbols as follows:</p>
<p><span class="math display">\[H_{0}: \mu_{1} = \mu_{2}\mbox{ or }\qquad  H_{0}: \mu_{1} -\mu_{2}=0\]</span></p>
<p>where <span class="math inline">\(\mu_{1}\)</span> is the average reading score for students in the control group (no intervention) and <span class="math inline">\(\mu_{2}\)</span> be the average reading score for students in the intervention group. Notice it can be written as one mean equals the other, but also as the difference between two means equaling zero. The alternative hypothesis <span class="math inline">\(H_{A}\)</span> states that there is a relationship:</p>
<p><span class="math display">\[H_{A}: \mu_{1} \neq \mu_{2} \qquad \mbox{ or } \qquad H_{A}: \mu_{1}-\mu_{2} \neq 0\]</span></p>
<section id="assumptions" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">5.3.1</span> Assumptions</h3>
<ul>
<li>The data distribution for each group is approximately normal.</li>
<li>The scores are independent within each group.</li>
<li>The scores from the two groups are independent of each other (i.e.&nbsp;the two samples are independent).</li>
</ul>
</section>
<section id="sampling-distribution-for-the-difference" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="sampling-distribution-for-the-difference"><span class="header-section-number">5.3.2</span> Sampling Distribution for the difference</h3>
<p>We use <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span> as a point estimate for <span class="math inline">\(\mu_1 - \mu_2\)</span>, which has a standard error of</p>
<p><span class="math display">\[
SE_{\bar{x}_1 - \bar{x}_2}
   = \sqrt{SE_{\bar{x}_1}^2 + SE_{\bar{x}_2}^2}
     = \sqrt{\frac{\sigma^{2}_{1}}{n_1} + \frac{\sigma^{2}_{2}}{n_2}}
\]</span></p>
<p>So the equations for a Confidence Interval is,</p>
<p><span class="math display">\[
  \left( \bar{x}_{1} - \bar{x}_{2} \right) \pm t_{\frac{\alpha}{2}, df}
    \sqrt{ \frac{\sigma^{2}_{1}}{n_{1}} + \frac{\sigma^{2}_{2}}{n_{2}} }
\]</span></p>
<p>and Test Statistic is,</p>
<p><span class="math display">\[
  t^{*} =  \frac{\left( \bar{x}_{1} - \bar{x}_{2} \right) - d_{0}}
       {\left( \sqrt{ \frac{\sigma^{2}_{1}}{n_{1}} + \frac{\sigma^{2}_{2}}{n_{2}} }
       \right )}
\]</span></p>
<p>Typically it is unlikely that the population variances <span class="math inline">\(\sigma^{2}_{1}\)</span> and <span class="math inline">\(\sigma^{2}_{2}\)</span> are known so we will use sample variances <span class="math inline">\(s^{2}_{1}\)</span> and <span class="math inline">\(s^{2}_{2}\)</span> as estimates.</p>
<p>While you may never hand calculate these equations, it is important to see the format, or structure, of the equations. Equation <span class="math inline">\(\ref{2sampCImean}\)</span> has the same format of</p>
<p><span class="math display">\[ \mbox{point estimate} \pm 2*\mbox{standard error}\]</span></p>
<p>regardless what it is we’re actually trying to estimate. Thus in a pinch, you can calculate approximate confidence intervals for whatever estimate you are trying to understand, given only the estimate and standard error, even if the computer program does not give it to you easily or directly.</p>
</section>
<section id="example-smoking-and-bmi" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="example-smoking-and-bmi"><span class="header-section-number">5.3.3</span> Example: Smoking and BMI</h3>
<p>We would like to know, is there convincing evidence that the average BMI differs between those who have ever smoked a cigarette in their life compared to those who have never smoked? This example uses the Addhealth dataset.</p>
<p><strong>1. Identify response and explanatory variables.</strong></p>
<ul>
<li>The quantitative response variable is BMI (variable )</li>
<li>The binary explanatory variable is whether the person has ever smoked a cigarette (variable )</li>
</ul>
<p><strong>2. Visualize and summarize bivariate relationship.</strong></p>
<div class="callout callout-style-simple callout-warning">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Using <code>na.omit()</code> is dangerous! This will remove ALL rows with ANY missing data in it. Regardless if the missing values are contained in the variables you are interested in. The example below employs a trick/work around to not have NA values show in the output. We take the data set <code>addhealth</code> <em>and then</em> <code>select</code> the variables we want to plot, <em>and then</em> we use <code>na.omit()</code> to delete all rows with missing data. Then that is saved as a new, temporary data frame specifically named for this case (<code>plot.bmi.smoke</code>).</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>note for later. Move this explanation into data viz section.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>plot.bmi.smoke <span class="ot">&lt;-</span> addhealth <span class="sc">%&gt;%</span> <span class="fu">select</span>(eversmoke_c, BMI) <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot.bmi.smoke, <span class="fu">aes</span>(<span class="at">x=</span>eversmoke_c, <span class="at">y=</span>BMI, <span class="at">fill=</span>eversmoke_c)) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_boxplot</span>(<span class="at">width=</span>.<span class="dv">3</span>) <span class="sc">+</span> <span class="fu">geom_violin</span>(<span class="at">alpha=</span>.<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Smoking status"</span>) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_fill_viridis_d</span>(<span class="at">guide=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">stat_summary</span>(<span class="at">fun.y=</span><span class="st">"mean"</span>, <span class="at">geom=</span><span class="st">"point"</span>, <span class="at">size=</span><span class="dv">3</span>, <span class="at">pch=</span><span class="dv">17</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="bivariate_analysis_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>plot.bmi.smoke <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(eversmoke_c) <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(BMI, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sd =</span> <span class="fu">sd</span>(BMI, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">IQR =</span> <span class="fu">IQR</span>(BMI, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  eversmoke_c  mean    sd   IQR
  &lt;fct&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Non Smoker   29.7  7.76  9.98
2 Smoker       28.8  7.32  9.02</code></pre>
</div>
</div>
<p>Smokers have an average BMI of 28.8, smaller than the average BMI of non-smokers at 29.7. Nonsmokers have more variation in their BMIs (sd 7.8 v. 7.3 and IQR 9.98 v. 9.02), but the distributions both look normal, if slightly skewed right.</p>
<p><strong>3. Write the relationship you want to examine in the form of a research question.</strong></p>
<ul>
<li>Null Hypothesis: There is no relationship between BMI and smoking status.</li>
<li>Alternate Hypothesis: There is a relationship between BMI and smoking status.</li>
</ul>
<p><strong>4. Perform an appropriate statistical analysis.</strong></p>
<p>I. Let <span class="math inline">\(\mu_1\)</span> denote the average BMI for nonsmokers, and <span class="math inline">\(\mu_2\)</span> the average BMI for smokers.</p>
<ol start="2" type="I">
<li><p><span class="math inline">\(\mu_1 - \mu_2 = 0\)</span> There is no difference in the average BMI between smokers and nonsmokers. <span class="math inline">\(\mu_1 - \mu_2 \neq 0\)</span> There is a difference in the average BMI between smokers and nonsmokers.</p></li>
<li><p>We are comparing the means between two independent samples. A Two-Sample T-Test for a difference in means will be conducted. The assumptions that the groups are independent is upheld because each individual can only be either a smoker or nonsmoker. The difference in sample means <span class="math inline">\(\bar{x_1} - \bar{x_2}\)</span> is normally distributed – this is a valid assumption due to the large sample size and that differences typically are normally distributed. The observations are independent, and the variability is roughly equal (IQR 9.9 v. 9.0).</p></li>
<li><p>We use the <code>t.test</code> function, but use model notation of the format <code>outcome</code> <span class="math inline">\(\sim\)</span> <code>category</code>. Here, <code>BMI</code> is our continuous outcome that we’re testing across the (binary) categorical predictor <code>eversmoke_c</code>.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(BMI <span class="sc">~</span> eversmoke_c, <span class="at">data=</span>addhealth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  BMI by eversmoke_c
t = 3.6937, df = 3395.3, p-value = 0.0002245
alternative hypothesis: true difference in means between group Non Smoker and group Smoker is not equal to 0
95 percent confidence interval:
 0.3906204 1.2744780
sample estimates:
mean in group Non Smoker     mean in group Smoker 
                29.67977                 28.84722 </code></pre>
</div>
</div>
<p>We have very strong evidence against the null hypothesis, <span class="math inline">\(p = 0.0002\)</span>.</p>
<p><strong>5. Write a conclusion in the context of the problem.</strong></p>
<p>On average, nonsmokers have a significantly higher BMI by 0.83 (0.39, 1.27) compared to nonsmokers (<span class="math inline">\(p = 0.0002\)</span>).</p>
<div class="callout callout-style-simple callout-warning">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Always check the output against the direction you are testing. R always will calculate a difference as group 1 - group 2, and it defines the groups alphabetically. For example, for a factor variable that has groups A and B, R will automatically calculate the difference as A-B. In this example it is Nonsmoker - Smoker.</p>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="bv-anova" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="bv-anova"><span class="header-section-number">5.4</span> (Q~C) Multiple means: ANOVA</h2>
<p>Frequently, a researcher wants to compare the means of an outcome across three or more treatments in a single experiment. We might initially think to do pairwise comparisons (1v2, 1v3, 2v3) for a total of three comparisons. However, this strategy can be treacherous. If we have many groups and do many comparisons, it is likely that we will eventually find a difference just by chance, even if there is no difference in the populations.</p>
<p>When we analyze a conventional two-treatment experiment, we are prepared to run a 1 in 20 risk of an apparently significant result arising purely by accident (the 5% chance of a Type I error). We regard such a risk as being fairly unlikely and feel justified in accepting with confidence any significant results we obtain.</p>
<p>Analyzing a single experiment as a series of 10 treatment pairs is a very different proposition. The chance of an apparently significant result arising purely by chance somewhere in the 10 analyses increases dramatically. Using a 5% error rate, the chance of NOT making at Type I error is .95. To not make a Type I error 10 times is <span class="math inline">\(.95^{10} = .6\)</span>. That means there is a 40% of making a Type I error! </p>
<section id="example-visual-comparison" class="level4" data-number="5.4.0.1">
<h4 data-number="5.4.0.1" class="anchored" data-anchor-id="example-visual-comparison"><span class="header-section-number">5.4.0.1</span> Example: Visual Comparison</h4>
<p>Examine the figure below. Compare groups I, II, and III. Can you visually determine if the differences in the group centers is due to chance or not? What about groups IV, V, and VI?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/toyANOVA.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Side-by-side dot plot for the outcomes for six groups.</figcaption><p></p>
</figure>
</div>
<p>So we need some method of comparing treatments for more than two groups at a time. This is done using an Analysis of Variance (ANOVA) model. ### Terminology</p>
<ul>
<li><strong>Response Variable</strong>: The response variable in the ANOVA setting is the quantitative (continuous) variable that we want to compare among the different treatments.</li>
<li><strong>Factor/Treatment</strong>: A property or characteristic (categorical variable) that allows us to distinguish the different populations from one another. An independent variable to be studied in an investigation such as temperature, type of plant, color of flower, location.</li>
<li><strong>Factor/Treatment level</strong>: Factors have different levels, such as 3 temperatures, 5 locations, 3 colors, etc.</li>
<li><strong>Within-sample Variation</strong>: Variation within a sample from one population. Individuals who receive the same treatment will experience identical experimental conditions. The variation within each of the treatment groups must therefore be a consequence of solely random variation.</li>
<li><strong>Between-sample Variation</strong>: Variation between samples. This is the difference between the group means. If some treatments are genuinely more effective than others, then we would expect to see relatively large differences between the treatment means and a relatively large between-treatments variation.</li>
</ul>
</section>
<section id="formulation-of-the-one-way-anova-model" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="formulation-of-the-one-way-anova-model"><span class="header-section-number">5.4.1</span> Formulation of the One-way ANOVA model</h3>
<p>ANOVA is a mathematical technique which uses a model based approach to partition the variance in an experiment into different sources of variance. This technique enables us to test if most the variation in the treatment means is due to differences between the groups.</p>
<p>Starting with our generic conceptual understanding of statistical models:</p>
<blockquote class="blockquote">
<p>DATA = MODEL + RESIDUAL</p>
</blockquote>
<p>our MODEL for this situation is the group membership. Does knowing what group an observation is in tell you about the location of the data? The one-way (or one-factor) ANOVA model is</p>
<p><span class="math display">\[
y_{ij} = \mu_{i} + \epsilon_{ij} \qquad \qquad
\epsilon_{ij} \overset{iid}{\sim} \mathcal{N}(0,\sigma^{2})
\]</span></p>
<p>for <span class="math inline">\(i=1, \ldots, I\)</span> factor levels and <span class="math inline">\(j = 1, \ldots, n_{i}\)</span> subjects within each factor level. The random error terms are independently and identically distributed (iid) normally with common variance.</p>
<p>The null and alternative hypotheses are always phrased as follows:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The mean outcome is the same across all groups. <span class="math inline">\(\mu_1 = \mu_2 = \cdots = \mu_k\)</span></li>
<li><span class="math inline">\(H_A\)</span>: At least one mean is different.</li>
</ul>
<p>How do we compare means using an <strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance? By comparing the portion of the variance in the outcome that is explained by the groups, to the portion that’s leftover due to unexplained randomness. Essentially we’re comparing the ratio of <code>MODEL</code> to <code>RESIDUAL</code>.</p>
<p>The total variation of the observed data is broken down into 2 parts:</p>
<blockquote class="blockquote">
<p>Total Variation = Between Group Variation + Within Group Variation</p>
</blockquote>
<p>Variation is measured using the Sum of Squares (SS): The sum of the squares within a group (SSE), the sum of squares between groups (SSG), and the total sum of squares (SST).</p>
<p><strong>SSG (Between groups)</strong>: Measures the variation of the <span class="math inline">\(I\)</span> group means around the overall mean. <span class="math display">\[
  SSG = \sum_{i=1}^{I}n_{i}(\bar{y}_{i.}-\bar{y}..)^{2} = n_{1}(\bar{y}_{1.}-\bar{y}..)^{2} + n_{2}(\bar{y}_{2.}-\bar{y}..)^{2} + n_{3}(\bar{y}_{3.}-\bar{y}..)^{2}
\]</span></p>
<p><strong>SSE (Within group)</strong>: Measures the variation of each observation around its group mean. <span class="math display">\[
SSE = \sum_{i=1}^{I}\sum_{j=1}^{n_{i}}(y_{ij}-\bar{y}_{i.})^{2} = \sum_{i=1}^{I}(n_{i}-1)Var(Y_{i})
\]</span></p>
<p><strong>SST (Total)</strong>: Measures the variation of the <span class="math inline">\(N\)</span> data points around the overall mean. <span class="math display">\[
SST =  \sum_{i=1}^{I}\sum_{j=1}^{n_{i}}(y_{ij}-\bar{y}..)^{2} = (N-1)Var(Y)
\]</span></p>
</section>
<section id="analysis-of-variance-table" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="analysis-of-variance-table"><span class="header-section-number">5.4.2</span> Analysis of Variance Table*:</h3>
<p>The results of an analysis of variance test are always summarized in an ANOVA table. The format of an ANOVA table is as follows:</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 35%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2">Source :========= Groups</td>
<td rowspan="2">SS :======: SSG</td>
<td rowspan="2">df :=====: <span class="math inline">\(I-1\)</span></td>
<td rowspan="2">MS :=========================: MSG = <span class="math inline">\(\frac{SSG}{I-1}\)</span></td>
<td rowspan="2">F | :=====:+ <span class="math inline">\(\frac{MSG}{MSE}\)</span></td>
</tr>
<tr class="even">
</tr>
<tr class="odd">
<td>Error</td>
<td>SSE</td>
<td><span class="math inline">\(N-I\)</span></td>
<td>MSE = <span class="math inline">\(\frac{MSG}{N-I}\)</span></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>SST</strong></td>
<td><span class="math inline">\(N-1\)</span></td>
<td colspan="2"><pre><code>  |</code></pre></td>
</tr>
</tbody>
</table>
</section>
<section id="the-f-distribution" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="the-f-distribution"><span class="header-section-number">5.4.3</span> The F-distribution</h3>
<p>The <span class="math inline">\(p\)</span>-value of the test is the <strong>area to the right</strong> of the F statistic density curve. This is always to the right because the F-distribution is not symmetric, truncated at 0 and skewed right. This is true regardless of the <span class="math inline">\(df\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="bivariate_analysis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="assumptions-1" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="assumptions-1"><span class="header-section-number">5.4.4</span> Assumptions</h3>
<p>Generally we must check three conditions on the data before performing ANOVA:</p>
<ul>
<li>The observations are independent within and across groups</li>
<li>The data within each group are nearly normal</li>
<li>The variability across the groups is about equal.</li>
</ul>
<p>When these three conditions are met, we may perform an ANOVA to determine whether the data provide strong evidence against the null hypothesis that all the <span class="math inline">\(\mu_i\)</span> are equal.</p>
</section>
<section id="example-a-comparison-of-plant-species-under-low-water-conditions" class="level3" data-number="5.4.5">
<h3 data-number="5.4.5" class="anchored" data-anchor-id="example-a-comparison-of-plant-species-under-low-water-conditions"><span class="header-section-number">5.4.5</span> Example: A comparison of plant species under low water conditions</h3>
<p>The <code>PLANTS1</code> data file gives the percent of nitrogen in four different species of plants grown in a laboratory. The researchers collected these data in parts of the country where there is very little rainfall. To examine the effect of water, they varied the amount per day from 50mm to 650mm in 100mm increments. There were 9 plants per species-by-water combination. Because the plants are to be used primarily for animal food, with some parts that can be consumed by people, a high nitrogen content is very desirable. Let’s formally test to see if the nitrogen content in the plants differ across species.</p>
<p><strong>1. Identify response and explanatory variables.</strong></p>
<ul>
<li>The quantitative response variable is % nitrogen (<code>pctnit</code>)</li>
<li>The categorical explanatory variable is species (<code>species</code>)</li>
</ul>
<p><strong>2. Visualize and summarize bivariate relationship.</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>plot.nitrogen.species <span class="ot">&lt;-</span> plants1 <span class="sc">%&gt;%</span> <span class="fu">select</span>(species, pctnit) <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot.nitrogen.species, <span class="fu">aes</span>(<span class="at">x=</span>species, <span class="at">y =</span> pctnit, <span class="at">fill=</span>species)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_boxplot</span>(<span class="at">width=</span>.<span class="dv">3</span>) <span class="sc">+</span> <span class="fu">geom_violin</span>(<span class="at">alpha=</span>.<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Species"</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_fill_viridis_d</span>(<span class="at">guide=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">stat_summary</span>(<span class="at">fun.y=</span><span class="st">"mean"</span>, <span class="at">geom=</span><span class="st">"point"</span>, <span class="at">size=</span><span class="dv">3</span>, <span class="at">pch=</span><span class="dv">17</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="bivariate_analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>plot.nitrogen.species <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(pctnit, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sd =</span> <span class="fu">sd</span>(pctnit, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">IQR =</span> <span class="fu">IQR</span>(pctnit, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">species</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">3.039810</td>
<td style="text-align: right;">0.2506118</td>
<td style="text-align: right;">0.2690</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">2.092841</td>
<td style="text-align: right;">0.2377523</td>
<td style="text-align: right;">0.2725</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">3.284365</td>
<td style="text-align: right;">0.3218599</td>
<td style="text-align: right;">0.5065</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">1.195587</td>
<td style="text-align: right;">0.2342217</td>
<td style="text-align: right;">0.3125</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>While the standard deviations are relatively similar across all species, the means are different (3.04 v. 2.09 v. 3.28 v. 1.20), with species 3 having the largest mean nitrogen content and species 4 the smallest. Species 3 has the highest IQR and species 1 has the lowest 0.506 v.&nbsp;0.269).</p>
<p><strong>3. Write the relationship you want to examine in the form of a research question.</strong></p>
<ul>
<li>Null Hypothesis: There is no difference in the average nitrogen content among plant species 1 through 4.</li>
<li>Alternative Hypothesis: There is a difference in the average nitrogen content among plant species 1 through 4.</li>
</ul>
<p><strong>4. Perform an appropriate statistical analysis.</strong></p>
<p>I. Let <span class="math inline">\(\mu_{1}\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(\mu_{4}\)</span> be the mean nitrogen content in plant species 1 through 4 respectively.</p>
<ol start="2" type="I">
<li><p><span class="math inline">\(H_{0}: \mu_{1} = \mu_{2} = \mu_{3} = \mu_{4}\)</span><br>
<span class="math inline">\(H_{A}:\)</span> At least one mean is different.</p></li>
<li><p>We are comparing means from multiple groups, so an ANOVA is the appropriate procedure. We need to check for independence, approximate normality and approximately equal variances across groups.</p></li>
</ol>
<p><strong>Independence:</strong> We are assuming that each plant was sampled independently of each other, and that the species themselves are independent of each other.</p>
<p><strong>Normality:</strong> With grouped data it’s easier to look at the histograms than qqplots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plants1, <span class="fu">aes</span>(<span class="at">x=</span>pctnit, <span class="at">fill=</span>species)) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">""</span>) <span class="sc">+</span> <span class="fu">geom_density</span>() <span class="sc">+</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(species<span class="sc">~</span>.) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks=</span><span class="cn">NULL</span>) <span class="sc">+</span> <span class="fu">scale_fill_viridis_d</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="bivariate_analysis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>The distributions per group tend to follow an approximate normal distribution.</p>
<p><strong>Equal variances:</strong> One way to assess if the groups have approximately equal variances is by comparing the IQR across groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plants1 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">IQR =</span> <span class="fu">IQR</span>(pctnit), <span class="at">SD =</span> <span class="fu">sd</span>(pctnit)) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">species</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">IQR</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">0.2690</td>
<td style="text-align: right;">0.2506118</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">0.2725</td>
<td style="text-align: right;">0.2377523</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">0.5065</td>
<td style="text-align: right;">0.3218599</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.2342217</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The IQRs are similar so assumption of equal variances is not grossly violated. We can proceed with the ANOVA procedure.</p>
<ol start="4" type="I">
<li>We use the <code>aov(response $\sim$ predictor)</code> function on the relationship between the nitrogen levels and tree species. We then pipe in <code>summary()</code> to make the output display nicely.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(pctnit<span class="sc">~</span>species, <span class="at">data=</span>plants1) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
species       3 172.39   57.46   827.5 &lt;2e-16 ***
Residuals   248  17.22    0.07                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>5. Write a conclusion in the context of the problem.</strong> The results of the ANOVA test indicate that at least one species has a different average nitrogen content than the other varieties (<span class="math inline">\(p&lt;\)</span>.001).</p>
</section>
<section id="coefficient-of-determination-r2" class="level3" data-number="5.4.6">
<h3 data-number="5.4.6" class="anchored" data-anchor-id="coefficient-of-determination-r2"><span class="header-section-number">5.4.6</span> Coefficient of determination <span class="math inline">\(R^{2}\)</span></h3>
<p>The coefficient of determination is defined as <span class="math inline">\(R^{2} = \frac{SSG}{SST}\)</span> and can be interpreted as the % of the variation seen in the outcome that is due to subject level variation within each of the treatment groups. The strength of this measure can be thought of in a similar manner as the correlation coefficient <span class="math inline">\(r\)</span>: <span class="math inline">\(&lt; .3\)</span> indicates a poor fit, <span class="math inline">\(&lt; .5\)</span> indicates a medium fit, and <span class="math inline">\(&gt; .7\)</span> indicates a good fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fl">172.39</span><span class="sc">/</span>(<span class="fl">172.39+17.22</span>)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 90.9182</code></pre>
</div>
</div>
<p>A large amount (91%) of the variation seen in nitrogen content in the plant can be explained by the species of plant.</p>
</section>
<section id="multiple-comparisons" class="level3" data-number="5.4.7">
<h3 data-number="5.4.7" class="anchored" data-anchor-id="multiple-comparisons"><span class="header-section-number">5.4.7</span> Multiple Comparisons</h3>
<p>Suppose that an ANOVA test reveals that there is a difference in at least one of the means. How can we determine which groups are significantly different without increasing our chance of a Type I error?</p>
<p>Simple! We perform all the pairwise comparisons but using a test statistic that retains a <strong>family-wise error rate</strong> of 0.05 (or our chosen <span class="math inline">\(\alpha\)</span>). There are different methods to adjust for multiple comparisons, we will be using the <strong>Tukey HSD (honest significant difference) test</strong>. Continuing on with the analysis of nitrogen across plant species.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(pctnit<span class="sc">~</span>species, <span class="at">data=</span>plants1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = pctnit ~ species, data = plants1)

$species
          diff        lwr        upr   p adj
2-1 -0.9469683 -1.0684156 -0.8255209 0.0e+00
3-1  0.2445556  0.1231082  0.3660029 2.4e-06
4-1 -1.8442222 -1.9656696 -1.7227748 0.0e+00
3-2  1.1915238  1.0700764  1.3129712 0.0e+00
4-2 -0.8972540 -1.0187014 -0.7758066 0.0e+00
4-3 -2.0887778 -2.2102252 -1.9673304 0.0e+00</code></pre>
</div>
</div>
<p>The results from Tukey’s HSD for all pairwise comparisons indicate that the average nitrogen content in one species is significantly different from each of the three other species. The nice benefit of this procedure is that the difference between the means of the two groups are compared, and a 95confidence interval for each difference is included. So specifically, species 2 has on average 0.94 (0.82, 1.09) lower percent nitrogen compared to species 1 (<span class="math inline">\(p&lt;.0001\)</span>). Also, species 3 has on average 1.19 (1.07, 1.31) higher percent nitrogen compared to species 2 (<span class="math inline">\(p&lt;.0001\)</span>).</p>
<hr>
</section>
</section>
<section id="bv-chisq" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="bv-chisq"><span class="header-section-number">5.5</span> (C~C) Multiple Proportions: <span class="math inline">\(\chi^{2}\)</span></h2>
<p>Recall that the point estimates for the proportion of an event occurring is <span class="math inline">\(\frac{x}{n}\)</span>, where <span class="math inline">\(x\)</span> is the number of times the event occurs out of <span class="math inline">\(n\)</span> records. In this section we we would like to make conclusions about the difference in two population proportions: <span class="math inline">\(p_1 - p_2\)</span>. In other words we’re testing the hypothesis that <span class="math inline">\(p_{1}-p_{2}=0\)</span>.</p>
<p>Our estimate for the difference in proportions based on the sample is <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>. No surprise there. What is slightly different is that we use a <strong>pooled proportion</strong> to check the condition of normality, and to calculate the standard error of the estimate. This pooled proportion is calculated by pooling the number of events in both groups, divided by the effective sample size for those groups.</p>
<p><span class="math display">\[ \hat{p} = \frac{x_{1} + x_{2}}{n_{1}+n_{2}} \]</span></p>
<p>Then the standard error of the point estimate is calculated as</p>
<p><span class="math display">\[ \sqrt{\frac{\hat{p}(1-\hat{p})}{n_1} + \frac{\hat{p}(1-\hat{p})}{n_2}} \]</span></p>
<p>So the equations for the Confidence Interval for the difference in proportions is,</p>
<p><span class="math display">\[
\left( \hat{p}_{1} - \hat{p}_{2} \right) \pm t_{\frac{\alpha}{2}, df}
\sqrt{\frac{\hat{p}(1-\hat{p})}{n_1} + \frac{\hat{p}(1-\hat{p})}{n_2}}
\]</span></p>
<p>with test statistic, <span class="math display">\[
t^{*} =  \frac{\left( \hat{p}_{1} - \hat{p}_{2} \right) - d_{0}}
        {\left( \sqrt{\frac{\hat{p}(1-\hat{p})}{n_1} + \frac{\hat{p}(1-\hat{p})}{n_2}}
        \right )}
\]</span></p>
<section id="conditions-for-the-sampling-distribution-to-be-normal." class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="conditions-for-the-sampling-distribution-to-be-normal."><span class="header-section-number">5.5.1</span> Conditions for the sampling distribution to be normal.</h3>
<p>The difference <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> tends to follow a normal model when 1) each proportion separately follows a normal model, and 2) the two samples are independent of each other. #1 can be verified by checking the <strong>success-failure condition</strong> for each group.</p>
<p>That means:</p>
<ul>
<li><span class="math inline">\(\hat{p}n_{1} \geq 10\)</span>, AND</li>
<li><span class="math inline">\(\hat{p}n_{2} \geq 10\)</span>, AND</li>
<li><span class="math inline">\(\hat{q}n_{1} \geq 10\)</span>, AND</li>
<li><span class="math inline">\(\hat{q}n_{1} \geq 10\)</span>.</li>
</ul>
<p>Where, if I’ve forgotten to mention it yet, <span class="math inline">\(q = 1-p\)</span>.</p>
<p>When sample sizes are below 10, but still not <em>super</em> small, say like 5, we turn to the non-parameteric version of this test called a <strong>Fisher’s Exact Test</strong>.</p>
</section>
<section id="example-are-mammograms-effective" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="example-are-mammograms-effective"><span class="header-section-number">5.5.2</span> Example: Are Mammograms effective?</h3>
<p>This example comes from the <a href="https://www.openintro.org/stat/textbook.php?stat_book=os">OpenIntro Statistics</a> textbook (3rd ed).</p>
<p>A 30-year study was conducted with nearly 90,000 female participants. [(Miller AB. 2014)][mammo] During a 5-year screening period, each woman was randomized to one of two groups: in the first group, women received regular mammograms to screen for breast cancer, and in the second group, women received regular non-mammogram breast cancer exams. No intervention was made during the following 25 years of the study, and we’ll consider death resulting from breast cancer over the full 30-year period. Results from the study are summarized in the following table.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>footnote not working</p>
<p>mammo Twenty five year follow-up for breast cancer incidence and mortality of the Canadian National Breast Screening Study: randomized screening trial. BMJ 2014;348:g366.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Alive</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Dead</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">44405</td>
<td style="text-align: right;">505</td>
<td style="text-align: right;">44910</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mammogram</td>
<td style="text-align: right;">44425</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">44925</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">88830</td>
<td style="text-align: right;">1005</td>
<td style="text-align: right;">89835</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><br></p>
<p>The independent/explanatory variable is treatment (additional mammograms), and the dependent/response variable is death from breast cancer. Are these measures associated?</p>
<p>If mammograms are much more effective than non-mammogram breast cancer exams, then we would expect to see additional deaths from breast cancer in the control group (there is a relationship). On the other hand, if mammograms are not as effective as regular breast cancer exams, we would expect to see no difference in breast cancer deaths in the two groups (there is no relationship).</p>
<p>What we need to do is to figure out how many deaths would be <strong>expected</strong>, if there was no relationship between treatment death by breast cancer, and then examine the <strong>residuals</strong> - the difference between the observed (<span class="math inline">\(O_{ij}\)</span>) and expected (<span class="math inline">\(E_{ij}\)</span>).</p>
<p>In our DATA = MODEL + RESIDUAL framework, the DATA is the observed counts <span class="math inline">\(O_{ij}\)</span>, and the MODEL is the expected counts <span class="math inline">\(E_{ij}\)</span>.</p>
<p>To see how the expected counts are calculated, we need to define a few more symbols, so we can find our way around the cells of a table. Just like rows and columns in a matrix, rows are indexed first (as <span class="math inline">\(i\)</span> and columns indexed as <span class="math inline">\(j\)</span>). So the cell in the top left is <span class="math inline">\(i=1\)</span> and <span class="math inline">\(j=1\)</span>.</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 1%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(O_{ij}\)</span></th>
<th style="text-align: center;">Alive</th>
<th style="text-align: center;">Dead</th>
<th colspan="2" style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mammo</td>
<td style="text-align: center;"><span class="math inline">\(n_{11}\)</span></td>
<td colspan="3" style="text-align: center;"><span class="math inline">\(n_{12}\)</span> | <span class="math inline">\(n_{1.}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Control</td>
<td style="text-align: center;"><span class="math inline">\(n_{21}\)</span></td>
<td colspan="3" style="text-align: center;"><span class="math inline">\(n_{22}\)</span> | <span class="math inline">\(n_{2.}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;"><span class="math inline">\(n_{.1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{.2}\)</span></td>
<td colspan="2" style="text-align: center;"><span class="math inline">\(N\)</span></td>
</tr>
</tbody>
</table>
<p>The expected count for each cell is calculated as the row total times the column total for that cell, divided by the overall total. Yes this will end up as a fraction.</p>
<p><span class="math display">\[E_{ij} = \frac{n_{i.}n_{.j}}{N}\]</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Alive</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Dead</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">44407.58</td>
<td style="text-align: right;">502.4161</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mammogram</td>
<td style="text-align: right;">44422.42</td>
<td style="text-align: right;">502.5839</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The residuals are calculated as <span class="math display">\[ RESIDUALS = (O_{ij} - E_{ij})\]</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Alive</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Dead</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">-0.0122616</td>
<td style="text-align: right;">0.1152775</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mammogram</td>
<td style="text-align: right;">0.0122596</td>
<td style="text-align: right;">-0.1152583</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Examining the residuals can tell us which combinations had counts more or less observations than expected. If mammograms were not associated with survival, there were 0.01 fewer people still alive than expected, and 0.11 more people dead. This is trivially small (2 x 2) example with very large sample sizes. There will be another example provided later.</p>
<p>The <span class="math inline">\(\chi^2\)</span> test statistic is defined as the sum of the squared residuals, divided by the expected counts, and follows a <span class="math inline">\(\chi^2\)</span> distribution with degrees of freedom (#rows -1)(#cols -1).</p>
<p><span class="math display">\[ \sum_{ij}\frac{(O_{ij}-E_{ij})^{2}}{E_{ij}} \]</span></p>
<p>Like every other statistical test, large values of test statistics correspond to low p-values.</p>
<p>Below is a picture of the distribution for the current example. The p-value is reported on the left (vertically), the purple shaded area denotes the rejection region if we were using a hard cutoff of 0.05. (The rejection region is the area where the test statistic had to be at for a p-value to be smaller than .05.). For this example the test statistic was 0.017, which corresponds to a p-value of 0.895. Thus, this study does not provide enough evidence to support the claim that mammograms decrease the rate of deaths by breast cancer.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="bivariate_analysis_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="example-smoking-and-general-health" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="example-smoking-and-general-health"><span class="header-section-number">5.5.3</span> Example: Smoking and General Health</h3>
<p>More often than not, we will have the full data available. That is, data at each individual record not just a summary table like in the previous example. Let’s work through an example.</p>
<p>Using the Addhealth data set, what can we say about the relationship between smoking and a person’s perceived general level of general health?</p>
<p><strong>1. Identify response and explanatory variables.</strong></p>
<ul>
<li>The binary explanatory variable is whether the person has ever smoked an entire cigarette (<code>eversmoke_c</code>)</li>
<li>The categorical explanatory variable is the person’s general health (<code>genhealth</code>) and has levels “Excellent”, “Very Good”, “Good”, “Fair”, and “Poor”.</li>
</ul>
<p><strong>2. Visualize and summarise bivariate relationship.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_xtab</span>(<span class="at">grp=</span>addhealth<span class="sc">$</span>eversmoke_c, <span class="at">x=</span>addhealth<span class="sc">$</span>genhealth, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">show.total =</span> <span class="cn">FALSE</span>, <span class="at">margin=</span><span class="st">"row"</span>, <span class="at">legend.title=</span><span class="st">""</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="bivariate_analysis_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>The percentage of smokers seems to increase as the general health status decreases. Almost three-quarters (73%, n=40) of those reporting poor health have smoked an entire cigarette at least once in their life compared to 59% (n=573) of those reporting excellent health.</p>
<p><strong>3. Write the relationship you want to examine in the form of a research question.</strong></p>
<p>Is the proportion of those who have ever smoked equal across all levels of general health?</p>
<ul>
<li>Null Hypothesis: The proportion of smokers in each general health category is the same.</li>
<li>Alternate Hypothesis: At least one proportion is different.</li>
</ul>
<p><strong>4. Perform an appropriate statistical analysis.</strong></p>
<p>I. Define the parameters under consideration.</p>
<ul>
<li>Let <span class="math inline">\(p_{1}\)</span> be the true proportion of smokers within the ``Excellent” health category.</li>
<li>Let <span class="math inline">\(p_{2}\)</span> be the true proportion of smokers within the ``Very good” health category.</li>
<li>Let <span class="math inline">\(p_{3}\)</span> be the true proportion of smokers within ``Good” health category.</li>
<li>Let <span class="math inline">\(p_{4}\)</span> be the true proportion of smokers within ``Fair” health category.</li>
<li>Let <span class="math inline">\(p_{5}\)</span> be the true proportion of smokers within ``Poor” health category.</li>
</ul>
<ol start="2" type="I">
<li><p><span class="math inline">\(H_{0}: p_{1} = p_{2} = p_{3} = p_{4} = p_{5}\)</span><br>
<span class="math inline">\(H_{A}:\)</span> At least one proportion is different.</p></li>
<li><p>I will conduct a <span class="math inline">\(\chi\)</span>-squared test of association. There is at least 10 observations in each combination of smoking status and general health.</p></li>
<li><p>Conduct the test.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>health.smoke.model <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(addhealth<span class="sc">$</span>genhealth, addhealth<span class="sc">$</span>eversmoke_c)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>health.smoke.model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  addhealth$genhealth and addhealth$eversmoke_c
X-squared = 30.795, df = 4, p-value = 3.371e-06</code></pre>
</div>
</div>
<p>We have strong evidence against the null; the <span class="math inline">\(p\)</span>-value is less than .0001.</p>
<p><strong>5. Write a conclusion in context of the problem.</strong> We can conclude that there is an association between ever smoking a cigarette in their life and perceived general health (<span class="math inline">\(\chi^2\)</span> = 30.8, df=4, <span class="math inline">\(p&lt;.0001\)</span>).</p>
</section>
<section id="multiple-comparisons-1" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="multiple-comparisons-1"><span class="header-section-number">5.5.4</span> Multiple Comparisons</h3>
<p>Just like with ANOVA, if we find that the chi-squared test indicates that at least one proportion is different from the others, it’s our job to figure out which ones might be different! We will analyze the residuals to accomplish this. Not by hand! Never again! You’re not learning how to code for nothing.</p>
<p>The residuals are automatically stored in the model output. You can either print them out and look at the values directly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>health.smoke.model<span class="sc">$</span>residuals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   addhealth$eversmoke_c
addhealth$genhealth Non Smoker     Smoker
          Excellent  3.4461139 -2.5168277
          Very good  0.4810893 -0.3513578
          Good      -2.4431255  1.7843072
          Fair      -1.0556365  0.7709714
          Poor      -0.9446378  0.6899048</code></pre>
</div>
</div>
<p>Or you can extract them and save them as a data frame. Then use ggplot with <code>geom_raster</code> to fill in your squares.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>plot.residuals <span class="ot">&lt;-</span> health.smoke.model<span class="sc">$</span>residuals <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot.residuals, <span class="fu">aes</span>(<span class="at">x=</span>addhealth.genhealth, <span class="at">y=</span>addhealth.eversmoke_c)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Freq)) <span class="sc">+</span>  <span class="fu">scale_fill_viridis_c</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="bivariate_analysis_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The proportion of those who have never smoked and report being in Excellent health is higher than expected if these two measures were independent (high positive residual means observed is greater than expected). A lower percent of people reporting Good health never smoked, which is lower than expected if smoking and health status were independent. So these two categories are likely to be the groups that have a different proportion of lifetime smoker <span class="math inline">\(p_{i}\)</span> compared to the other groups.</p>
</section>
</section>
<section id="bv-corr" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="bv-corr"><span class="header-section-number">5.6</span> (Q~Q) Correlation</h2>
<p>The <strong>correlation coefficient</strong> is designated by <span class="math inline">\(r\)</span> for the sample correlation, and <span class="math inline">\(\rho\)</span> for the population correlation. The correlation is a measure of the strength and direction of a <em>linear relationship</em> between two variables.</p>
<p>The correlation ranges from +1 to -1. A correlation of +1 means that there is a perfect, positive linear relationship between the two variables. A correlation of -1 means there is a perfect, negative linear relationship between the two variables. In both cases, knowing the value of one variable, you can perfectly predict the value of the second.</p>
<section id="strength-of-the-correlation" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="strength-of-the-correlation"><span class="header-section-number">5.6.1</span> Strength of the correlation</h3>
<p>Here are rough estimates for interpreting the strengths of correlations based on the magnitude of <span class="math inline">\(r\)</span>.</p>
<ul>
<li><span class="math inline">\(|r| \geq 0.7\)</span>: Very strong relationship</li>
<li><span class="math inline">\(0.4 \leq |r| &lt; 0.7\)</span>: Strong relationship</li>
<li><span class="math inline">\(0.3 \leq |r| &lt; 0.4\)</span>: Moderate relationship</li>
<li><span class="math inline">\(0.2 \leq |r| &lt; 0.3:\)</span> Weak relationship</li>
<li><span class="math inline">\(|r| &lt; 0.2:\)</span> Negligible or no relationship</li>
</ul>
</section>
<section id="example-federal-spending-per-capita-and-poverty-rate" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="example-federal-spending-per-capita-and-poverty-rate"><span class="header-section-number">5.6.2</span> Example: Federal spending per capita and poverty rate</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ggplot(county, aes(x=poverty, y=fed_spend00)) +</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  geom_point() + ylab("federal spending per capita") +</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  xlab("poverty rate")</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#cor(county$poverty, county$fed_spend00, use="complete.obs")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>There is a negligible, positive, linear relationship between poverty rate and per capita federal spending (<span class="math inline">\(r = 0.03\)</span>).</li>
<li>Let <span class="math inline">\(\rho\)</span> denote the true correlation between poverty rate and federal spending per capita.</li>
<li>Our null hypothesis is that there is no correlation between poverty rate and federal spending (<span class="math inline">\(\rho = 0\)</span>), and the alternative hypothesis is that they are correlated (<span class="math inline">\(\rho \neq 0\)</span>).</li>
<li>We can use the <code>cor.test()</code> function to analyze the evidence in favor of this alternative hypothesis.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#cor.test(county$poverty, county$fed_spend00)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We conclude from this that there was a non-statistically significant, negligible correlation between poverty and federal spending (<span class="math inline">\(r = 0.03 (-0.0003, .069), p = 0.05\)</span>).</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./foundations.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Foundations for Inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This page is built with ❤️ and <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>



</body></html>