{
  "hash": "98daa311948d0930be2749f654002ab7",
  "result": {
    "engine": "knitr",
    "markdown": "# Generalized Linear Models {#sec-glm}\n\n:::{.callout-note}\n#### Packages Used\nThis chapter uses the following packages:\n[ggplot2](https://ggplot2.tidyverse.org),\n[gtsummary](https://www.danieldsjoberg.com/gtsummary/),\n[pander](https://cran.r-project.org/web/packages/pander/vignettes/pander.html),\n[MKmisc](https://cran.r-project.org/web/packages/MKmisc/vignettes/MKmisc.html),\n[survey](http://r-survey.r-forge.r-project.org/survey/),\nthe [AddHealth](https://www.norcalbiostat.com/data/#AddHealth) and cleaned 'depression' data set.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nOne of the primary assumptions with linear regression, is that the error terms have a specific distribution. Namely: \n\n$$ \\epsilon_{i} \\sim \\mathcal{N}(0, \\sigma^{2}) \\qquad i=1, \\ldots, n, \\quad \\mbox{and } \\epsilon_{i} \\perp \\epsilon_{j}, i \\neq j $$\n\nWhen your outcome variable $y$ is non-continuous/non-normal, the above assumption fails dramatically. \n\nGeneralized Linear Models (GLM) allows for different data type outcomes by allowing the linear portion of the model ($\\mathbf{X}\\beta$) to be related to the outcome variable $y$ using a _link_ function, that allows the magnitude of the variance of the errors ($\\sigma$) to be related to the predicted values themselves. \n\nThere are a few overarching types of non-continuous outcomes that can be modeled with GLM's. \n\n* Binary data: Logistic or Probit regression (@sec-logreg)\n* Log-linear models (@sec-log-linear)\n* Multinomial/categorical data: Multinomial or Ordinal Logistic regression.  (@sec-multinomial-reg)\n* Count data: Poisson regression (@sec-poisson-reg)\n\n\n\n\n## Fitting GLMs \n\nAll regression models aim to model the expected value of the response variable $Y$ given the observed data $X$, through some link function $C$ \n\n$$E(Y|X) = C(X)$$ \n\nDepending on the data type of $Y$, this link function takes different forms. Examples include: \n\n* Linear regression: C = Identity function (no change)\n* Logistic regression: C = logit function\n* Poisson regression: C = log function\n\n\n**R**\n\nThe general syntax is similar to `lm()`, with the additional required `family=` argument. See `?family` for a list of options. Example for Logistic regression would be: \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm(y ~ x1 + x2 + x3, data=DATA, family=\"binomial\") \n```\n:::\n\n\n\n\n\n**SPSS**\n\nFile menu: `Regression` --> Binary Logistic. \n\nSyntax: \n\n```\nlogistic regression Y with x1 x2 x3\n   /categorical = x2\n```\n[IBM](https://www.ibm.com/support/knowledgecenter/en/SSLVMB_26.0.0/statistics_reference_project_ddita/spss/regression/syn_logistic_regression_overview.html) - reference\n\n**Stata**\n\n`logistic Y x1 x2`\n\n[Stata](https://www.stata.com/features/overview/logistic-regression/) - reference\n\n\n## Log-linear models {#sec-log-linear}\n\nA *log-linear* model is when the log of the response variable is modeled using a linear combination of predictors. \n\n$$ln(Y) \\sim XB +\\epsilon$$\n\nRecall that in statistics, when we refer to the _log_, we mean the natural log _ln_.\n\nThis type of model is often use to model count data using the Poisson distribution (@sec-poisson-reg).\n\nWhy are we transforming the outcome? Typically to achieve normality when the response variable is highly skewed. \n\n**Interpreting results**\n\nSince we transformed our outcome before performing the regression, we have to back-transform the coefficient before interpretation. Similar to logistic regression, we need to _exponentiate_ the regression coefficient before interpreting. \n\nWhen using log transformed outcomes, the effect on Y becomes **multiplicative** instead of additive. \n\n* **Additive** For every 1 unit increase in X, y increases by b1\n* **Multiplicative** For every 1 unit increase in X, y is multiplied by $e^{b1}$\n\nExample: Let $b_{1} = 0.2$. \n\n* **Additive** For every 1 unit increase in X, y increases by 0.2 units.\n* **Multiplicative** For every 1 unit increase in X, y changes by $e^{0.2} = 1.22$ = 22%\n\n\nThus we interpret the coefficient as a **percentage** change in $Y$ for a unit increase in $x_{j}$.\n\n* **$b_{j}<0$** : Positive slope, positive association. The expected value of $Y$ for when $x=0$ is $1 - e^{b_{j}}$ percent _lower_ than when $x=1$\n* **$b_{j} \\geq 0$** : Negative slope, negative association. The expected value of $Y$ for when $x=0$ is $e^{b_{j}}$ percent _higher_ than when $x=1$\n\n\n::: {.callout-tip}\n## Learn more\n[This](https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faqhow-do-i-interpret-a-regression-model-when-some-variables-are-log-transformed/) UCLA resource is my \"go-to\" reference on how to interpret the results when your response, predictor, or both variables are log transformed. \n\n:::\n\n\n### Example\n\nWe are going to analyze personal income from the AddHealth data set. First I need to clean up, and log transform the variable for personal earnings `H4EC2` by following the steps below _in order_. \n\n1. Remove values above 999995 (structural missing). \n3. Create a new variable called `income`, that sets all values of personal income to be NA if below the federal poverty line. \n    - First set `income= H4EC2`\n    - Then set income to missing, if `H4EC2 < 10210` (the federal poverty limit from 2008)\n4. Then create a new variable: `logincome` that is the natural log (_ln_) of income. e.g. `addhealth$logincome = log(addhealth$income)`\n\nWhy are we transforming income? To achieve normality. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\nhist(addhealth$income, probability = TRUE); lines(density(addhealth$income, na.rm=TRUE), col=\"red\")\nhist(addhealth$logincome, probability = TRUE); lines(density(addhealth$logincome, na.rm=TRUE), col=\"blue\")\nqqnorm(addhealth$income); qqline(addhealth$income, col=\"red\")\nqqnorm(addhealth$logincome); qqline(addhealth$logincome, col=\"blue\")\n```\n\n::: {.cell-output-display}\n![](glm_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Identify variables**\n\n* Quantitative outcome that has been log transformed: Income (variable `logincome`)\n* Binary predictor: Ever smoked a cigarette (variable `eversmoke_c`)\n* Binary confounder: Gender (variable `female_c`)\n \nThe mathematical multivariable model looks like: \n\n$$ln(Y) \\sim \\beta_{0} + \\beta_{1}x_{1} + \\beta_{2}x_{2}$$\n\n**Fit a linear regression model**\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nln.mod.2 <- lm(logincome~wakeup + female_c, data=addhealth)\nsummary(ln.mod.2) %>% pander()\n```\n\n::: {.cell-output-display}\n\n------------------------------------------------------------------\n       &nbsp;         Estimate   Std. Error   t value   Pr(>|t|)  \n-------------------- ---------- ------------ --------- -----------\n  **(Intercept)**      10.65       0.026       409.8        0     \n\n     **wakeup**       -0.01491    0.003218    -4.633    3.73e-06  \n\n **female_cFemale**   -0.1927      0.017      -11.34    2.564e-29 \n------------------------------------------------------------------\n\n\n---------------------------------------------------------------\n Observations   Residual Std. Error    $R^2$    Adjusted $R^2$ \n-------------- --------------------- --------- ----------------\n     3813             0.5233          0.03611       0.0356     \n---------------------------------------------------------------\n\nTable: Fitting linear model: logincome ~ wakeup + female_c\n\n\n:::\n\n```{.r .cell-code}\n1-exp(confint(ln.mod.2)[-1,])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    2.5 %      97.5 %\nwakeup         0.02099299 0.008561652\nfemale_cFemale 0.20231394 0.147326777\n```\n\n\n:::\n:::\n\n\n\n\n\n**Interpret the results**\n\n* For every hour later one wakes up in the morning, one can expect to earn `1-exp(-0.015)` = 1.4% less income than someone who wakes up one hour earlier. This is after controlling for gender. \n* Females have on average `1-exp(-0.19)` = 17% percent lower income than males, after controlling for the wake up time. \n\nBoth gender and time one wakes up are significantly associated with the amount of personal earnings one makes. Waking up later in the morning is associated with 1.4% (95% CI 0.8%-2%, p<.0001) percent lower income than someone who wakes up one hour earlier. Females have 17% (95% CI 15%-20%, p<.0001) percent lower income than males. \n\n\n## Binary outcome data\n\nConsider an outcome variable $Y$ with two levels: Y = 1 if event, = 0 if no event. \n\nLet $p_{i} = P(y_{i}=1)$. \n\nTwo goals: \n\n* Assess the impact selected covariates have on the probability of an outcome occurring. \n* Predict the probability of an event occurring given a certain covariate pattern. This is covered in @sec-binary-classification\n\nBinary data can be modeled using a _Logistic Model_ or a _Probit Model_. \n\nThe logistic model relates the probability of an event based on a linear combination of X's. \n\n$$\nlog\\left(\n\\frac{p_{i}}{1-p_{i}}\n\\right) = \\beta_{0} + \\beta_{1}x_{1i} + \\beta_{2}x_{2i} + \\ldots + \\beta_{p}x_{pi}\n$$\n\nSince the _odds_ are defined as the probability an event occurs divided by the  probability it does not occur: $(p/(1-p))$, the function $log\\left(\\frac{p_{i}}{1-p_{i}}\\right)$ is also known as the _log odds_, or more commonly called the **_logit_**. This is the _link_ function for the logistic regression model. \n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nThis in essence takes a binary outcome 0/1 variable, turns it into a continuous probability (which only has a range from 0 to 1) Then the logit(p) has a continuous distribution ranging from $-\\infty$ to $\\infty$, which is the same form as a Multiple Linear Regression (continuous outcome modeled on a set of covariates)\n\n\nThe probit function uses the inverse CDF for the normal distribution as the link function. The effect of the transformation is very similar. For social science interpretation of the coefficients, we tend to choose the _logit_ transformation and conduct a Logistic Regression. For classification purposes, often researchers will test out both transformations to see which one gives the best predictions. \n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](glm_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n\n\n\n\n## Logistic Regression {#sec-logreg}\n\nSince the link between $X$ and $Y$ is no longer linear, a one unit increase in $X_{p}$ is no longer associated with a $b_{p}$ increase in $Y$. The regression coefficients $b_{p}$ from a logistic regression must be _exponentiated_ before interpretation.  \n\n$$OR = e^{b}$$\n\nThe Odds Ratio (OR) provides a directly understandable statistic for the relationship between $y$ and a specific $x$ given all other $x$'s in the model are fixed. A later example in @sec-mlogreg provides a numeric example of how Odds Ratios are calculated. \n\nIn testing for a relationship between $x$ and $y$, our hypothesis is that $\\beta_{p}=0$. Since $e^{0}=1$, the reference value for the Odds Ratio that signifies no relationship, is 1, not 0. \n\n\n### Interpreting Odds Ratios\n\nConsider a binary outcome with values YES, coded as 1, and NO, coded as 0. \n\n* **OR = 1** = equal chance of response variable being YES given any explanatory variable value. You are not able to predict participants’ responses by knowing their explanatory variable value. This would be a non significant model when looking at the p-value for the explanatory variable in the parameter estimate table.\n* **OR > 1** = as the explanatory variable value increases, the presence of a YES response is more likely. We can say that when a participant’s response to the explanatory variable is YES (1), they are more likely to have a response that is a YES (1). \n* **OR <1** = as the explanatory variable value increases, the presence of a YES response is less likely. We can say that when a participant’s response to the explanatory variable is YES (1) they are less likely to have a response that is a YES (1). \n\nFor a continuous variable X with slope coefficient $\\beta$, the quantity $e^{b}$ is interpreted as the ratio of the odds for a person with value (X+1) relative to the odds for a person with value X. \n\n\n### Confidence Intervals {#sec-or-ci}\n\nConfidence intervals are a range for the population’s predicted odds ratio based on the sample data. We are 95% confident that any given population’s odds ratio would range between those two values. \n\nThe OR is **not** a linear function of the $x's$, but $\\beta$ is. This means that a CI for the OR is created by calculating a CI for $\\beta$, and then exponentiating the endpoints. A 95% CI for the OR is calculated as: \n\n$$e^{\\hat{\\beta} \\pm 1.96 SE_{\\beta}} $${#eq-or-ci}\n\n\nThis math holds for any $k$ unit change in x. The linearity of the confidence interval only applies at the untransformed level of the $\\beta$'s. NOT the odds ratio. \n\n\n### Example: The effect of gender on Depression {#sec-logreg-dep-ex}\n\nThis uses a cleaned version of the depression data set from PMAS6. \n\n* Binary outcome variable: Symptoms of Depression (`cases`)\n* Binary predictor variable: Gender (`sex`) as an indicator of being female\n\nThe outcome $y$ is a 0/1 Bernoulli random variable. The sum of a vector of Bernoulli's ($\\sum_{i=1}^{n}y_{i}$) has a Binomial distribution. When we specify that `family = \"binomial\"` the `glm()` function auto-assigns \"logit\" link function. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndep_sex_model <- glm(cases ~ sex, data=depress_clean, family=\"binomial\")\nsummary(dep_sex_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cases ~ sex, family = \"binomial\", data = depress_clean)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -3.3511     0.6867  -4.880 1.06e-06 ***\nsex           1.0386     0.3767   2.757  0.00583 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 268.12  on 293  degrees of freedom\nResidual deviance: 259.40  on 292  degrees of freedom\nAIC: 263.4\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n\n\nWe exponentiate the coefficients to back transform the $\\beta$ estimates into Odds Ratios\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(dep_sex_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         sex \n 0.03504558  2.82517483 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(dep_sex_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %    97.5 %\n(Intercept) 0.008071827 0.1225716\nsex         1.399110558 6.2142384\n```\n\n\n:::\n:::\n\n\n\n\n\nFemales have 2.8 (1.4, 6.2) times the odds of showing signs of depression compared to males. \n\n\n### Multiple Logistic Regression {#sec-mlogreg}\nLet's continue with the depression model, but now also include age and income as potential predictors of symptoms of depression. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmvmodel <- glm(cases ~ age + income + sex, data=depress_clean, family=\"binomial\")\nsummary(mvmodel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cases ~ age + income + sex, family = \"binomial\", \n    data = depress_clean)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept) -1.60590    0.84654  -1.897  0.05782 . \nage         -0.02096    0.00904  -2.318  0.02043 * \nincome      -0.03656    0.01409  -2.595  0.00946 **\nsex          0.92945    0.38582   2.409  0.01600 * \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 268.12  on 293  degrees of freedom\nResidual deviance: 247.54  on 290  degrees of freedom\nAIC: 255.54\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n\n\n* The sign of the $\\beta$ coefficients can be interpreted in the same manner as with linear regression as having a positive or negative relationship.  \n* The odds of being depressed are less if the respondent has a higher income and is older, and higher if the respondent is female. \n\n> The odds of a female being depressed are 2.53 times greater than the odds for Males after adjusting for the effects of age and income (p=.016). \n\n**Example calculation for $OR = e^{\\beta}$**\n\nThe full model is: \n$$log(odds) = -0.676 - 0.02096*age - .03656*income + 0.92945*gender$$\n\nWe want to calculate the Odds Ratio of depression for women compared to men. \n$$ OR = \\frac{Odds (Y=1|F)}{Odds (Y=1|M)} $$\n\nWrite out the equations for men and women separately. \n$$ = \\frac{e^{-0.676 - 0.02096*age - .03656*income + 0.92945(1)}}\n          {e^{-0.676 - 0.02096*age - .03656*income + 0.92945(0)}}$$\n\nApplying rules of exponents to simplify.\n$$ = \\frac{e^{-0.676}e^{- 0.02096*age}e^{- .03656*income}e^{0.92945(1)}}\n          {e^{-0.676}e^{- 0.02096*age}e^{- .03656*income}e^{0.92945(0)}}$$\n\n$$ = \\frac{e^{0.92945(1)}}\n          {e^{0.92945(0)}}$$\n\n$$ = e^{0.92945} $$\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(.92945)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.533116\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(coef(mvmodel)[4])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sex \n2.533112 \n```\n\n\n:::\n:::\n\n\n\n\n\n### Effect of a k unit change \n\n* Sometimes a 1 unit change in a continuous variable is not meaningful. \n* $exp(kb)$ is the incremental odds ratio corresponding to an increase of $k$ units in the variable X, assuming that the values of all other X variables remain unchanged. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(mvmodel, exponentiate=TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lyzzvcinij\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lyzzvcinij table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lyzzvcinij thead, #lyzzvcinij tbody, #lyzzvcinij tfoot, #lyzzvcinij tr, #lyzzvcinij td, #lyzzvcinij th {\n  border-style: none;\n}\n\n#lyzzvcinij p {\n  margin: 0;\n  padding: 0;\n}\n\n#lyzzvcinij .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lyzzvcinij .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lyzzvcinij .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lyzzvcinij .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lyzzvcinij .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lyzzvcinij .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lyzzvcinij .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lyzzvcinij .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lyzzvcinij .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lyzzvcinij .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lyzzvcinij .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lyzzvcinij .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lyzzvcinij .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lyzzvcinij .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lyzzvcinij .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyzzvcinij .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lyzzvcinij .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lyzzvcinij .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lyzzvcinij .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyzzvcinij .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lyzzvcinij .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyzzvcinij .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lyzzvcinij .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyzzvcinij .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lyzzvcinij .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lyzzvcinij .gt_left {\n  text-align: left;\n}\n\n#lyzzvcinij .gt_center {\n  text-align: center;\n}\n\n#lyzzvcinij .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lyzzvcinij .gt_font_normal {\n  font-weight: normal;\n}\n\n#lyzzvcinij .gt_font_bold {\n  font-weight: bold;\n}\n\n#lyzzvcinij .gt_font_italic {\n  font-style: italic;\n}\n\n#lyzzvcinij .gt_super {\n  font-size: 65%;\n}\n\n#lyzzvcinij .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lyzzvcinij .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lyzzvcinij .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lyzzvcinij .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lyzzvcinij .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lyzzvcinij .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lyzzvcinij .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;OR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>OR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.98</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.96, 1.00</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.020</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">income</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.96</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.94, 0.99</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.009</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">2.53</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.23, 5.66</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.016</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n* The Adjusted odds ratio (AOR) for increase of 1 year of age is 0.98 (95%CI .96, 1.0)\n* How about a 10 year increase in age? $e^{10*\\beta_{age}} = e^{-.21} = .81$\n\nIn generalized linear models, the assumptions on $\\beta$ having a normal distribution.\n\nRefer back to @eq-or-ci, the linearity of the relationship is on the $\\beta$ level, not the odds ratio. Do all transformations on the $\\beta$'s, then the last step is the non-linear transformation of exponentiation. \n\nSo the mathematical order of operations is important! First use `coef` to extract the coefficients out of the model object (here named `mvmodel`), then pull the 2nd item out `coef(mvmodel)[2]`, then multiply it by 10, then lastly exponentiate this value. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(10*coef(mvmodel)[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age \n0.8109285 \n```\n\n\n:::\n:::\n\n\n\n\n\nDo the same to calculate the confidence interval for a 10 year time span. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(exp(10*confint(mvmodel)[2,]),3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5 % 97.5 % \n 0.676  0.965 \n```\n\n\n:::\n:::\n\n\n\n\n\nControlling for gender and income, an individual has 0.81 (95% CI 0.68, 0.97) times the odds of being depressed compared to someone who is 10 years younger than them. \n\n\n### Example: Predictors of smoking status\n\nConsider a logistic model on smoking status (0= never smoked, 1=has smoked) using gender, income, and blood pressure class (`bp_class`) as predictors. \n\n$$\nlogit(Y) = \\beta_{0} + \\beta_{1}\\mbox{(female)} + \\beta_{2}\\mbox{(income)} + \\beta_{3}\\mbox{(Pre-HTN)} \n+ \\beta_{4}\\mbox{(HTN-I)} + \\beta_{5}\\mbox{(HTN-II)}\n$$\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbp.mod <- glm(smoke ~ female_c + income + bp_class, data=addhealth, family='binomial')\ntbl_regression(bp.mod, exponentiate=TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"clvygbtzha\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#clvygbtzha table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#clvygbtzha thead, #clvygbtzha tbody, #clvygbtzha tfoot, #clvygbtzha tr, #clvygbtzha td, #clvygbtzha th {\n  border-style: none;\n}\n\n#clvygbtzha p {\n  margin: 0;\n  padding: 0;\n}\n\n#clvygbtzha .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#clvygbtzha .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#clvygbtzha .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#clvygbtzha .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#clvygbtzha .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#clvygbtzha .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#clvygbtzha .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#clvygbtzha .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#clvygbtzha .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#clvygbtzha .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#clvygbtzha .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#clvygbtzha .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#clvygbtzha .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#clvygbtzha .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#clvygbtzha .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clvygbtzha .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#clvygbtzha .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#clvygbtzha .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#clvygbtzha .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clvygbtzha .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#clvygbtzha .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clvygbtzha .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#clvygbtzha .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clvygbtzha .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#clvygbtzha .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#clvygbtzha .gt_left {\n  text-align: left;\n}\n\n#clvygbtzha .gt_center {\n  text-align: center;\n}\n\n#clvygbtzha .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#clvygbtzha .gt_font_normal {\n  font-weight: normal;\n}\n\n#clvygbtzha .gt_font_bold {\n  font-weight: bold;\n}\n\n#clvygbtzha .gt_font_italic {\n  font-style: italic;\n}\n\n#clvygbtzha .gt_super {\n  font-size: 65%;\n}\n\n#clvygbtzha .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#clvygbtzha .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#clvygbtzha .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#clvygbtzha .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#clvygbtzha .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#clvygbtzha .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#clvygbtzha .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;OR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>OR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">female_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.54</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.46, 0.63</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">income</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.00</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.00, 1.00</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.005</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">bp_class</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Normal</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Pre-HTN</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.08</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.92, 1.26</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    HTN-I</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.98</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.79, 1.21</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.8</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    HTN-II</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.03</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">0.71, 1.50</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.9</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\nIt is unlikely that blood pressure is associated with smoking status, all groups are not statistically significantly different from the reference group (all p-values are large). Let's test that hypothesis formally using a Wald Test. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey::regTermTest(bp.mod, \"bp_class\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWald test for bp_class\n in glm(formula = smoke ~ female_c + income + bp_class, family = \"binomial\", \n    data = addhealth)\nF =  0.428004  on  3  and  3723  df: p= 0.73294 \n```\n\n\n:::\n:::\n\n\n\n\n\nThe Wald Test has a large p-value of 0.73, thus blood pressure classification is not associated with smoking status.\n\n* This means blood pressure classification should not be included in a model to explain smoking status. \n\n\n### Model Fit \n\n::: {.callout-tip appearance=minimal}\nSee PMA6 12.8\n:::\n\n**Pseudo $R^{2}$**\n\nRecall in linear regression, the coefficient of determination $R^{2}$ could be used as a measure of model fit, as it represents the proportion of variance in the outcome explained by the model. This statistic can't be calculated for Logistic regression, but several versions of a _Pseudo $R^{2}$_ have been proposed, and are printed as part of the output for many statistical packages such as Stata. \n\n\n**Goodness of Fit**\n\nAnother way to assess model fit for the entire model is to perform a _goodness-of-fit_ test. The one developed by Hosmer and Lemeshow (1980) is the most commonly used GoF test. In this approach,\n\n1. the predicted probability of belonging to the event group (y=1) is calculated for every observation. \n2. these probabilities are sorted in ascending order, then divided into $j$ equal sized subgroups, typically deciles to create 10 'bins'. \n3. For each 'bin', or range of probabilities, count the observed number of individuals with the event (y=1) ($O_{j}$).\n4. For each 'bin', calculate the expected number of events by adding the predicted probabilities in that bin. ($E_{j}$)\n\nThe goodness of fit statistic is then calculated as follows: \n\n$$ GoF \\chi^{2} = \\sum_{j} \\frac{(O_{j}-E_{j})^2}{E_{j}} $$\n\nwhich approximately follows a $\\chi_{J-2}^{2}$ distribution under relatively large sample sizes. \n\n> A large GoF statistic (or small p-value) indicate that the fit may *NOT* be good\n\nR package: `MKmisc`, function `HLgof.test`. \n\n```\nMkmisc::HLgof.test(fit=fitted(model), obs=model$y)\n```\n\n**Accurate predictions**\n\nSince the logistic regression is all about modeling the probability of an event occurring, we can use that model to create predicted probabilities. The next chapter discusses how to use a logistic regression model for prediction, and what measures of fit are used to assess how \"accurate\" the model is. \n\n\n\n\n\n## Count outcome data {#poisson-reg}\n\nLets consider modeling the distribution of the number of of occurrences of a rare event in a specified period of time\n    - e.g. Number of thunderstorms in a year\n\n* If we assume:\n    * Rate ($\\mu$) is fixed over time\n    * Successive occurrences independent of each other\n\nThen we can use the **Poisson distribution**.\n\n$$\nP(Y=y) = e^{-\\mu}\\frac{\\mu^{y}}{y!}\n$$\n\n* The Poisson distribution has a distinct feature where the mean of the distribution $\\mu$, is also the variance. \n\n![Plot of Histogram of a Poisson Distribution with a Mean of 5 and a Normal Curve](images/poisson.png)\n\n\n### Poisson Regression {#sec-poisson-reg}\n\n::: {.callout-warning appearance=simple}\nThis section is still under development\n:::\n\n\nJust another GLM - we use a $ln$ as the link function. This lets us model the log rates using a linear combination of covariates. \n\n$$\n  ln(\\mu) = \\mathbf{X}\\beta\n$$\n\nThen the expected rate of events per unit of time is: \n\n$$\n  \\mu = e^{\\mathbf{X}\\beta}\n$$\n\nThis model assumes that the time of \"exposure\" for each record is identical. \n\n* Number of cigarettes per month\n* Number of epileptic seizures per week\n* Number of people with lung cancer in four cities\n    \nIf this is not the case (often), then this model needs to include an _offset_. \n\n* e.g. observing each patient for epileptic seizures for a different number of days\n* accounting for different sizes or structures of populations of interest (e.g. different cities with lung cancer)\n  \n\nWhat actually gets fit in `glm` is the model of expected _counts_, rather than rates, with an offset for the time period $T$. \n\n* If all time periods are the same, then T is constant, and a linear combination of the intercept, thus dropped from the model. \n\n$$\n  ln(\\lambda) = \\mathbf{X}\\beta + ln(T)\n$$\n\nWhile this offset will be added to the regression model as if it were another variable, it's not quite the same because the regression coefficient for the $ln(T)$ term is fixed at 1. \n\nThe generic formula for fitting a poisson model using `glm` is: \n\n```r\nglm(y ~ x1 + x2 + offset(log(T)), family='poisson')\n```\nor alternatively as an argument\n\n```r\nglm(y ~ x1 + x2, offset = log(T),  family='poisson')\n```\n\nThe interpretation of the $\\beta$ regression coefficients are differences in the log rate (or the log rate-ratio). So, just like with a logistic regression often we back-transform the coefficients by exponentiating before interpreting. So $e^{\\beta}$ is now the rate-ratio. \n\n* The intercept term is not a ratio, but a baseline rate when all covariates are 0\n* For other covariates, the coefficient is the relative change _per unit_ change in the covariate. \n    - one year older\n    - males vs females\n    \nAlso, similar to logistic regression, since the outcome was transformed, the standard errors are not useful or interpretable as is. To calculate confidence intervals for the rate ratios, \n\n1. calculate the CI for $\\beta$\n2. exponentiate each end point. \n\n\n\n### Example: Modeling counts from the Add Health Wave IV dataset. \n\nLet's model the number of siblings someone has, based off their age at Wave 1 (2008).\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nVisualize\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(addhealth, aes(x=nsib)) + geom_histogram() + \n  xlab(\"Number of siblings\") + ylab(\"Count\")\n```\n\n::: {.cell-output-display}\n![](glm_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnsib.model <- glm(nsib ~ agew1 + female, data=addhealth, family=\"poisson\")\ntbl_regression(nsib.model, exponentiate = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tzvgyaitze\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tzvgyaitze table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tzvgyaitze thead, #tzvgyaitze tbody, #tzvgyaitze tfoot, #tzvgyaitze tr, #tzvgyaitze td, #tzvgyaitze th {\n  border-style: none;\n}\n\n#tzvgyaitze p {\n  margin: 0;\n  padding: 0;\n}\n\n#tzvgyaitze .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tzvgyaitze .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tzvgyaitze .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tzvgyaitze .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tzvgyaitze .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tzvgyaitze .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tzvgyaitze .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tzvgyaitze .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tzvgyaitze .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tzvgyaitze .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tzvgyaitze .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tzvgyaitze .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tzvgyaitze .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tzvgyaitze .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tzvgyaitze .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tzvgyaitze .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tzvgyaitze .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tzvgyaitze .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tzvgyaitze .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tzvgyaitze .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tzvgyaitze .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tzvgyaitze .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tzvgyaitze .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tzvgyaitze .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tzvgyaitze .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tzvgyaitze .gt_left {\n  text-align: left;\n}\n\n#tzvgyaitze .gt_center {\n  text-align: center;\n}\n\n#tzvgyaitze .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tzvgyaitze .gt_font_normal {\n  font-weight: normal;\n}\n\n#tzvgyaitze .gt_font_bold {\n  font-weight: bold;\n}\n\n#tzvgyaitze .gt_font_italic {\n  font-style: italic;\n}\n\n#tzvgyaitze .gt_super {\n  font-size: 65%;\n}\n\n#tzvgyaitze .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tzvgyaitze .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tzvgyaitze .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tzvgyaitze .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tzvgyaitze .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tzvgyaitze .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tzvgyaitze .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;IRR&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>IRR</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">agew1</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.05</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.03, 1.06</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.10</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">1.06, 1.14</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> IRR = Incidence Rate Ratio, CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n## Categorical outcome data {#sec-multinomial-reg}\n\n\n::: {.callout-warning appearance=simple}\nThis section is still under development\n:::\n\n\nIf you want to keep the response variable as a categorical variable with more than two levels, the following regression model types are available: \n\n\n* [Ordinal Logistic Regression](https://stats.oarc.ucla.edu/r/dae/ordinal-logistic-regression/)\n* [Multinomial Regression](https://stats.oarc.ucla.edu/r/dae/multinomial-logistic-regression/)\n\n",
    "supporting": [
      "glm_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}